service: apollo-lambda
provider:
  name: aws
  runtime: nodejs12.x
functions:
  graphql:
    handler: handler.graphqlHandler
    environment:
      SAMPLE_ID: ${env:SAMPLE_ID}
      SAMPLE_KEY: ${env:SAMPLE_KEY}
      BUCKET: ${env:BUCKET}
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true